In [1]:
import pandas as pd
import numpy as np
import math

# Solution A:

In [32]:
# Solution for section-A:
MTRA=np.array([1,2,3])
MTRB=np.array([4,5,6])
MTRC=np.array([-1,1,3])

In [33]:
#1: 2A-B
SolutionMTRA_1=np.subtract(np.multiply(2,A),B)
SolutionA_1

array([-2, -1,  0])

In [6]:
#2:||A|| and the angle of A relative to the positive X-axis
magnitude_mtr==MTRA=np.linalg.norm(A)

In [34]:
X=np.arccos(A[0]/magnitude_A)
X
Sol_MTRA2=np.rad2deg(Unit_X)
Sol_MTRA2

74.498640433063

In [8]:
#3: A, Unit vector in direction of A
SolutionMTRA_3=np.divide(A,magnitude_A)
SolutionMTRA_3

array([0.26726124, 0.53452248, 0.80178373])

In [9]:
#4:direction cosine A
mag_MTRA=np.linalg.norm(A)
cos_a=np.divide(A[0],mag_A)
cos_b=np.divide(A[1],mag_A)
cos_C=np.divide(A[2],mag_A)
deg_a=np.rad2deg(cos_alpha)
deg_b=np.rad2deg(cos_beta)
deg_c=np.rad2deg(cos_gamma)

In [35]:
cos_sq_a=np.divide((1+math.cos(2*deg_alpha)),2)
cos_sq_alpha_deg=np.rad2deg(cos_sq_alpha)
cos_sq_alpha_deg

48.810674127003

In [11]:
cos_sq_beta =np.divide((1+math.cos(2*deg_beta)),2)
cos_sq_beta_deg=np.rad2deg(cos_sq_beta)
cos_sq_beta_deg

28.381697711393596

In [12]:
cos_sq_gamma=np.divide((1+math.cos(2*deg_gamma)),2)
cos_sq_gamma_deg=np.rad2deg(cos_sq_gamma)
cos_sq_gamma_deg

8.11040603802566

In [36]:
SolutionMTRA_4=np.sum([cos_sq_alpha_deg,cos_sq_beta_deg,cos_sq_gamma_deg],dtype=np.int32)
SolutionMTRA_4

84

In [14]:
#5: A.B and B.A

In [15]:
Solution_AB=np.dot(A,B)
Solution_AB

32

In [50]:
Solution_MTRBA=np.dot(B,A)
Solution_MTRBA

32

In [51]:
Matrix_MTRA=[[1,2,3]]
Matrix_MTRB=[[4,5,6]]
Matrix_MTRC=[[-1,1,3]]

In [52]:
def angle_rowwise(MTRA, MTRB):
    X1 = np.einsum('ij,ij->i',Matrix_A,Matrix_B)
    X2 = np.linalg.norm(A,axis=0)
    X3 = np.linalg.norm(B,axis=0)
    X4 = X1 / (X2*X3)
    return np.arccos(np.clip(X4,-1.0,1.0))

In [55]:
radian_value=angle_rowwise(A, B)
deg_value=np.rad2deg(radian_value)
deg_value

array([12.93315449])

In [56]:
#7: vector perpendicular to A

In [57]:
Vec_AB=np.dot(A,B)
Vec_AC=np.dot(A,C)
Vec_BC=np.dot(B,C)
Sol_A7=[Vec_AB, Vec_AC,Vec_BC]
Sol_A7

[32, 10, 19]

Two vectors are perpendicular to each other when the dot product of those vectors is equal to 0. Therefore, none of the vectors is perpendicular to A as solved.

In [59]:
#8: A*B and B*A

In [60]:
Solution_B=np.cross(A,B)
Solution_AB

32

In [63]:
Solution_BC=np.cross(B,A)
Solution_BC

array([ 3, -6,  3])

In [64]:
#9: vector perpendicular to both A and B is A*B

In [65]:
AC=np.cross(A,B)
AC

array([-3,  6, -3])

Cross product of A and B is perpendicular to both A and B.

In [28]:
#10: linear dependency- A,B,C
L_AB= np.linalg.solve(A,B)
L_AC= np.linalg.solve(A,C)
L_BC= np.linalg.solve(B,C)
L_AB

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [66]:
L_AC

NameError: name 'L_AC' is not defined

In [67]:
#11: Transpose_of_A*B and A*Transpose_of_B

In [71]:
a_transpose=A.transpose()
Solution_ATB=np.dot(a_transpose,B)
Solution_ATB

32

In [72]:
b_transpose=A.transpose()
Solution_BTA=np.dot(A,b_transpose)
Solution_BTA

14

# Solution B:

In [73]:
#Creating the initial matrix for the solution section-B:
MTRA=np.mat("1 2 3;4 -2 3;0 5 -1")
MTRB=np.mat("1 2 1;2 1 -4;3 -2 1")
MTRC=np.mat("1 2 3;4 5 6;-1 1 3")

In [74]:
#1: 2A-B
Sol_B1=np.subtract((np.multiply(2,A)),B)
Sol_B1

array([-2, -1,  0])

In [238]:
#2: A.B and B.A

In [75]:
Solution_AB=np.dot(A,B)
Solution_AB

32

In [76]:
Solution_BA=np.dot(B,A)
Solution_BA

32

In [78]:
#3: Transpose_of_AB and transpose_of_B*transpose_of_C

In [79]:
transpose_AdotB=Solution_AB.transpose()
transpose_AdotB

32

In [80]:
transposeA=A.transpose()
transposeB=B.transpose()
Sol_BTR=np.dot(transposeB,transposeA)
Sol_BTR

32

In [153]:
#4: Determinants of A and C

In [87]:
A_det=np.linalg.det(A)
C_det=np.linalg.det(C)
A_det

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [85]:
C_det

NameError: name 'C_det' is not defined

In [88]:
#5: the matrix (A,B or C) in which the row vectors form an orthogonal set.
arrayA=np.array(A)
arrayB=np.array(B)
arrayC=np.array(C)
orthoA_r1r2=np.dot(array_A[0],array_A[1])
orthoA_r1r2

2

In [91]:
ortho_B_r0r1=np.dot(array_B[0],array_B[1])
ortho_B_r1r2

NameError: name 'ortho_B_r1r2' is not defined

In [92]:
ortho_B_r0r2=np.dot(array_B[0],array_B[2])
ortho_B_r1r3

NameError: name 'ortho_B_r1r3' is not defined

In [93]:
ortho_B_r1r2=np.dot(array_B[1],array_B[2])
ortho_B_r1r2

30

In [94]:
ortho_C_r0r1=np.dot(array_C[0],array_C[1])
ortho_C_r0r1

-1

Therefor, Matrix-B is which row vectors form an orthogonal set.

In [97]:
#6:Inverse of A and B

In [115]:
A_inverse=np.linalg.inv(MTRA)
B_inverse=np.linalg.inv(MTRB)
A_inverse

matrix([[-0.5 ,  0.5 ],
        [ 0.75, -0.25]])

In [116]:
B_inverse

matrix([[0.83333333, 0.33333333],
        [0.33333333, 0.33333333]])

# Solution C:

In [102]:
#Creating the initial matrix for the solution section-C:
MTRA=np.mat("1 2;3 2")
MTRB=np.mat("2 -2;-2 5")

In [104]:
#1: the eigenvalues and the corresponding eigenvectors of A
eigenvalueA,eigenvectorA=np.linalg.eig(MTRA)

In [105]:
eigenvalueA

array([-1.,  4.])

In [106]:
eigenvectorA

matrix([[-0.70710678, -0.5547002 ],
        [ 0.70710678, -0.83205029]])

In [108]:
#2: the matrix-inverse_of_V.A.V where V is composed of eigenvectors of A
eigenvalueA,vector_V=np.linalg.eig(MTRA)

In [109]:
inverse_V=np.linalg.inv(vector_V)
inverse_V

matrix([[-0.84852814,  0.56568542],
        [-0.72111026, -0.72111026]])

In [111]:
Solution_C2=np.multiply(inverse_V,MTRA,vector_V)
Solution_C2

matrix([[-0.84852814,  1.13137085],
        [-2.16333077, -1.44222051]])

In [112]:
#3: the dot product between the eigenvectors of A
dot_prod_A=np.dot(eigenvectorA,eigenvectorA)
dot_prod_A

matrix([[ 0.10776773,  0.85377073],
        [-1.08834841,  0.30007542]])

In [114]:
#4: the dot product between the eigenvectors of B
eigenvalueB,eigenvectorB=np.linalg.eig(MTRB)
dot_prod_B=np.dot(eigenvectorB,eigenvectorB)
dot_prod_B

matrix([[ 0.6, -0.8],
        [ 0.8,  0.6]])